import {
  Activity,
  BookOpen,
  BookText,
  Brain,
  Briefcase,
  CheckCircle2,
  ChefHat,
  Compass,
  Database,
  Dumbbell,
  Flame,
  History,
  Languages,
  Package,
  Rocket,
  Shield,
  Sparkles,
  Target,
  TrendingUp,
  Zap,
  Box,
  DollarSign,
  Wallet,
  Globe,
  Heart,
  Music,
  Camera,
  Coffee,
  Sun,
  Moon,
  Cloud,
  Gamepad2,
  Code2,
  Terminal,
  Lightbulb,
  ListTodo,
  Star,
  Trophy,
  GraduationCap,
  Smile,
  Users,
} from "lucide-react";

export const ICON_LIBRARY = {
  Operations: Briefcase,
  Health: Shield,
  Mind: Brain,
  Wealth: Database,
  Vault: Package,
  Planning: Compass,
  Food: ChefHat,
  Life: Sparkles,
  Fitness: Dumbbell,
  Languages: Languages,
  Library: BookOpen,
  Trading: TrendingUp,
  Activity: Activity,
  Tasks: CheckCircle2,
  Habits: Zap,
  Journal: BookText,
  Target: Target,
  History: History,
  Flame: Flame,
  Rocket: Rocket,
  Trophy: Trophy,
  Star: Star,
  Code: Code2,
  Terminal: Terminal,
  Globe: Globe,
  Heart: Heart,
  Music: Music,
  Camera: Camera,
  Coffee: Coffee,
  Lightbulb: Lightbulb,
  List: ListTodo,
  Wallet: Wallet,
  Dollar: DollarSign,
  DollarSign: DollarSign,
  Box: Box,
  Sun: Sun,
  Moon: Moon,
  Cloud: Cloud,
  Game: Gamepad2,
  University: GraduationCap,
  Smile: Smile,
  Users: Users,
} as const;

export type IconName = keyof typeof ICON_LIBRARY;

export const ICON_SIZES = {
  XS: 10,
  SM: 12,
  MD: 14,
  LG: 16,
  XL: 18,
  XXL: 20,
  HUG: 24,
} as const;

export type IconSize = (typeof ICON_SIZES)[keyof typeof ICON_SIZES];
