import {
  Activity,
  BookOpen,
  BookText,
  Brain,
  Briefcase,
  CalendarDays,
  CheckCircle2,
  ChefHat,
  Compass,
  Database,
  Dumbbell,
  Flame,
  History,
  Languages,
  LayoutDashboard,
  Library,
  Package,
  Rocket,
  Shield,
  ShoppingCart,
  Sparkles,
  Target,
  TrendingUp,
  User,
  Users,
  Zap,
  Box,
  DollarSign,
  Wallet,
  Globe,
  Heart,
  Music,
  Camera,
  Coffee,
  Sun,
  Moon,
  Cloud,
  Gamepad2,
  Code2,
  Terminal,
  Flag,
  Lightbulb,
  ListTodo,
  Star,
  Trophy
} from "lucide-react";

export const ICON_LIBRARY = {
  "Operations": Briefcase,
  "Health": Shield,
  "Mind": Brain,
  "Wealth": Database,
  "Vault": Package,
  "Planning": Compass,
  "Food": ChefHat,
  "Life": Sparkles,
  "Fitness": Dumbbell,
  "Languages": Languages,
  "Library": BookOpen,
  "Trading": TrendingUp,
  "Activity": Activity,
  "Tasks": CheckCircle2,
  "Habits": Zap,
  "Journal": BookText,
  "Target": Target,
  "History": History,
  "Flame": Flame,
  "Rocket": Rocket,
  "Trophy": Trophy,
  "Star": Star,
  "Code": Code2,
  "Terminal": Terminal,
  "Globe": Globe,
  "Heart": Heart,
  "Music": Music,
  "Camera": Camera,
  "Coffee": Coffee,
  "Lightbulb": Lightbulb,
  "List": ListTodo,
  "Wallet": Wallet,
  "Dollar": DollarSign,
  "Box": Box,
  "Sun": Sun,
  "Moon": Moon,
  "Cloud": Cloud,
  "Game": Gamepad2,
} as const;

export type IconName = keyof typeof ICON_LIBRARY;
